# 应用服务 WEB 访问端口
server.port=8080

Mybatis-plus.mapper-locations=classpath*:/mapper/*.xml
#支持将执行的sql语句输出到控制台，便于观察对数据库的操作
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.name=defaultDataSource
spring.datasource.url=jdbc:mysql://localhost:3306/weixin?serverTimezone=UTC&rewriteBatchedStatements=true
spring.datasource.username=
spring.datasource.password=

server.servlet.session.timeout=3600

defaultImagesDir=D:\\weixin\\img\\images\\static\\
foodImagesDir=D:\\weixin\\img\\images\\static\\uploads\\images\\

host=http://localhost:8080

